### ISSUE TITLE
Check SWIG version before building

### ISSUE THREAD

**Issue by hemberger** [moble/GWFrames#47]
GWFrames can successfully build using an unsupported version of swig (e.g. swig 2.0.7 on Orca). However, some GWFrames functions will then segfault (which isn't terribly surprising since it's unsupported).

I think it shouldn't be too hard to check the swig version (with `swig -version`) during the build process to make sure it meets the minimum requirements. This would provide a useful error message instead of a segfault, which would be a nice improvement.

I can work on this if you'd like, Mike, but I wanted to report it first in case you had a particular idea about how/if you wanted to address this issue.

**Comment by vijayvarma392** [comment]
I second this. On Wheeler, I found that the default swig version (3.0.12) does not work but 3.0.10 does. And I had to figure this out through trial and error.

With Swig 3.0.12, the build is successful but I get the following error when I try to import GWFrames:
------------------------------------------------------------------------------------------------
>>> import GWFrames
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "GWFrames/__init__.py", line 153, in <module>
    class _MetaWaveform(type(_Waveform)):
TypeError: Error when calling the metaclass bases
    type 'SwigPyObjectType' is not an acceptable base type
------------------------------------------------------------------------------------------------

**Comment by moble** [comment]
I'm not really maintaining GWFrames any more.  My newer module `scri` will soon have all the capabilities of GWFrames, so I'm focused on making that happen.  Pull requests are welcome, but I don't really have the time to figure this out.  Sorry.

**Comment by moble** [comment]
Swig version is pinned now; just use conda or docker and it works.
