### ISSUE TITLE
GWFrames on Wheeler?

### ISSUE THREAD

**Issue by nilsdeppe** [moble/GWFrames#50]
Hi Mike,

I'm trying to use GWFrames on Wheeler and something is going wrong. Here's what I've done:

1. Add SWIG 3.0.10 to the python/anaconda-2.4.11 module (verified using `swig -version`)
2. Install GWFrames by running `python setup.py install --user` in `GWFrames/Code`
3.  Ran Mark's `CoMDiff.py` script in the catalog paper's repo
4. Get the error:
```
Traceback (most recent call last):
  File "./CoMDiff.py", line 102, in <module>
    main()
  File "./CoMDiff.py", line 94, in main
    (have_data,mm)= ComputeMismatch(path)
  File "./CoMDiff.py", line 26, in ComputeMismatch
    wh_com = GW.ReadFromNRAR(os.path.join(path,'rhOverM_Asymptotic_GeometricUnits_CoM.h5','Extrapolated_N2.dir'))
  File "/home/nils/.local/lib/python2.7/site-packages/GWFrames/__init__.py", line 557, in ReadFromNRAR
    W.AppendHistory("# <previous_history>\n#" + OldHistory.replace('\n','\n#') + "# </previous_history>\n")
  File "/home/nils/.local/lib/python2.7/site-packages/GWFrames/__init__.py", line 305, in decorator
    ret = func(self, *args, **kwargs)
TypeError: in method '_Waveform_AppendHistory', argument 2 of type 'std::string const &'
```
I've found a related issue on SWIG: https://github.com/swig/swig/issues/620 and tried adding
```
%include std_string.i
using std::string;
```
to the `GWFrames.i` file but had no luck. Any ideas?

**Comment by moble** [comment]
I've never seen that error before.  In particular, `std::string` was the one container that I didn't have to do anything to get working.  Maybe the unicode discussion is on to something.  Could you add a new line before

    "/home/nils/.local/lib/python2.7/site-packages/GWFrames/__init__.py", line 557

Have it `print(OldHistory)` and `print(type(OldHistory))`.  If it's unicode, you might want to change the original line to something like

    W.AppendHistory("# <previous_history>\n#" + str(OldHistory).replace('\n','\n#') + "# </previous_history>\n")

or even

    W.AppendHistory(str("# <previous_history>\n#" + str(OldHistory).replace('\n','\n#') + "# </previous_history>\n"))

This might be related to changes in how `h5py` reads strings from files, which is where that `OldHistory` comes from.

**Comment by nilsdeppe** [comment]
Alright, they both seem to resolve that issue... Thank you! Now I get a segmentation fault :/

**Comment by moble** [comment]
I've gotten multiple reports of segfaults alright, but haven't gotten any more details from anyone.  If you can help track it down, I'd appreciate it.  :)

But on that point, are you sure that you're using the current version of this repo?  Apparently, the SimulationAnnex has two copies of GWFrames, including an (unecessary???) old fork, and even that was accidentally pointing to a slightly older commit where a segfault hadn't been fixed, ...  You know, the usual SXS nonsense.  So the point is, please make sure you're using the latest version.

Anyway, I'll change the code and close this.  And if you have any ideas on the segfault, please open an issue.
